### ISSUE TITLE
Are tests for Physical Dimensions generating false positive for flipped (negative gain) signals?

### ISSUE THREAD

**Issue by remomueller** [nsrr/edf-editor-translator#6]
From this discussion: https://sleepdata.org/replies/314

Also, from the EDF documentation, Digital Min and Max do have the constraint that the max is larger than the min, however that constraint isn't there for Physical Min and Max (Specifically in EDF+ specs):

http://www.edfplus.info/specs/edfplus.html

> 5. 'Digital maximum' must be larger than 'Digital minimum'. In case of a negative amplifier gain the corresponding 'Physical maximum' is smaller than the 'Physical minimum'. Check item 9 on how to apply the 'negativity upward' rule in Clinical Neurophysiology to the physical ordinary signal. 'Physical maximum' must differ from 'Physical minimum'. In case of uncalibrated signals, physical dimension is left empty (that is 8 spaces), while 'Physical maximum' and 'Physical minimum' must still contain different values (this is to avoid 'division by 0' errors by some viewers).

**Comment by StrongTSQ** [comment]
The false positive warning is disabled.
